// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfDAaI0IexyStJ0loMzU8LvS0tPPHMtoE',
    appId: '1:735953150088:web:f26a0d69ecbd2d2b16bf3d',
    messagingSenderId: '735953150088',
    projectId: 'resturant--softmare',
    authDomain: 'resturant--softmare.firebaseapp.com',
    storageBucket: 'resturant--softmare.appspot.com',
    measurementId: 'G-5435JYNK4Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAndf5GmoLd3TVan8ICpDAUPmPKhanh7gY',
    appId: '1:735953150088:android:d46ab1f31c1daf6416bf3d',
    messagingSenderId: '735953150088',
    projectId: 'resturant--softmare',
    storageBucket: 'resturant--softmare.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVeEJ3h7cL4VP61KSIEHYCcu_oxJZcm_k',
    appId: '1:735953150088:ios:04bea40b76e34c7716bf3d',
    messagingSenderId: '735953150088',
    projectId: 'resturant--softmare',
    storageBucket: 'resturant--softmare.appspot.com',
    iosBundleId: 'com.example.restaurantsoftware',
  );
}
